# docker-compose.yml

services:

  kafka:
    image: apache/kafka:latest
    ports:
      - 9092:9092
    cpus: 1.0
    mem_limit: 2g
    healthcheck:
      test: ["CMD", "/opt/kafka/bin/kafka-topics.sh", "--list", "--bootstrap-server", "kafka:9092"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - kafka_data:/tmp/kafka-logs
    environment:
      # KRaft settings
      KAFKA_NODE_ID: 0
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      # Listeners
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      # KAFKA_LISTENERS: PLAINTEXT://172.30.115.198:9092,CONTROLLER://:9093
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.30.115.198:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    networks:
      - kafka_default

  producer:
    build: 
      context: ./kafka-producer
      dockerfile: Containerfile
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: covid_data
    networks:
      - kafka_default

  consumer:
    build: 
      context: ./kafka-consumer
      dockerfile: Containerfile
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_TOPIC: covid_data
    networks:
      - kafka_default

volumes:
  kafka_data:
    driver: local

networks:
  kafka_default:
    driver: bridge